apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/arinaho-muleba/my-practice-K8s-cluster.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: "{{ .path.basename }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/arinaho-muleba/my-practice-K8s-cluster.git
        targetRevision: HEAD
        path: "apps/{{ .path.basename }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: local
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
