apiVersion: batch/v1
kind: Job
metadata:
  name: my-flyway-job
  namespace: local
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: my-flyway-job
    spec:
      restartPolicy: Never
      containers:
        - name: my-flyway-app-container
          image: flyway/flyway:latest
          env:
            - name: FLYWAY_URL
              value: "jdbc:postgresql://my-test-db-service:5432/mydb"
            - name: FLYWAY_USER
              value: "admin"
            - name: FLYWAY_PASSWORD
              value: "admin"
            - name: FLYWAY_LOCATIONS
              value: "filesystem:/flyway/sql"
          volumeMounts:
            - name: flyway-sql
              mountPath: /flyway/sql
          command:
            - sh
            - -c
            - |
              flyway migrate
      volumes:
        - name: flyway-sql
          configMap:
            name: my-flyway-migrations
