apiVersion: v1
kind: Service
metadata:
  name: my-test-db-service
  namespace: local
spec:
  selector:
    app: my-test-db
  type: NodePort
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
