apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flyway-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/arinaho-muleba/my-practice-K8s-cluster.git
    targetRevision: HEAD
    path: apps/my-flyway-app
  destination:
    server: https://kubernetes.default.svc
    namespace: local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
